# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "Configuration" = "0l5z4m2m6g1km2s83aij55c1h58bbgj693i2swjmzh88lkrwm4qx";
    "FileKit" = "1w004kvgbpz4sqmrc1w4km8xpd4dbsrxkry5yvcam3izc6lfa8js";
    "LoggerAPI" = "1fxjpg18namyf950l14xznb0z2k9src381vnnfyjjq9qsdi4pxw4";
    "Rainbow" = "0qq0nfbxr7qvb8z07ac1rd6c844pmc3sk707pw8hdl2pc707yryf";
    "swift-argument-parser" = "0wjpv91cjfg9jwarhn0ak6i2h7ijwv0l4k4n0pdd3rbg3sqv1107";
    "swift-log" = "1045r1nxrz86cmxygd5dms06ybgyhqfzlv01645x96m2ial92i79";
    "swift-system" = "0g24vjxixzhpk4mjmq6zsh8wjkl631msg0v3hgyh7bf45nf5wzd8";
    "swift-tools-support-core" = "15bnqchpqs3j9h4pvngmsg8zc976r1nqwdj47myfi6adqb38kl6j";
    "swift-vips" = "1qwf0vxi6i7p697c538hki855ahgwnj15nn4qi6v95qh98ywr6wq";
    "SwiftExif" = "0plg353b08b105jhajhkl8fys3zrpq3yh5h5sdqib3fcb01lq3s0";
  };
}
