---
{
   "kind": "pipeline",
   "name": "macOS",
   "platform": {
      "arch": "amd64",
      "os": "darwin"
   },
   "steps": [
      {
         "commands": [
            "echo $PATH",
            "brew bundle",
            "make lint"
         ],
         "name": "Lint",
         "pull": "always"
      },
      {
         "commands": [
            "make build"
         ],
         "name": "Build",
         "pull": "always"
      },
      {
         "commands": [
            "cp ./.build/x86_64-apple-macosx/debug/munin /Users/kradalby/bin/."
         ],
         "name": "Install on local system",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "commands": [
            "make publish"
         ],
         "name": "Publish",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ],
   "type": "exec"
}
...
