---
{
   "kind": "pipeline",
   "name": "macOS",
   "platform": {
      "arch": "amd64",
      "os": "darwin"
   },
   "steps": [
      {
         "commands": [
            "echo $HOME",
            "brew bundle",
            "make lint"
         ],
         "environment": {
            "PATH": "/Users/kradalby/go/bin:/Users/kradalby/.local/bin:/Users/kradalby/bin:/Users/kradalby/git/dotfiles/bin:/Users/kradalby/.cargo/bin:/Users/kradalby/.config/yarn/global/node_modules/.bin:/Users/kradalby/.npm-packages/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/Users/kradalby/.vim/plugged/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Lint",
         "pull": "always"
      },
      {
         "commands": [
            "make build"
         ],
         "environment": {
            "PATH": "/Users/kradalby/go/bin:/Users/kradalby/.local/bin:/Users/kradalby/bin:/Users/kradalby/git/dotfiles/bin:/Users/kradalby/.cargo/bin:/Users/kradalby/.config/yarn/global/node_modules/.bin:/Users/kradalby/.npm-packages/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/Users/kradalby/.vim/plugged/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Build",
         "pull": "always"
      },
      {
         "commands": [
            "cp ./.build/x86_64-apple-macosx/debug/munin /Users/kradalby/bin/."
         ],
         "name": "Install on local system",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "commands": [
            "make publish"
         ],
         "name": "Publish",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ],
   "type": "exec"
}
...
