pipeline:
  lint:
    image: kradalby/swift-mint:latest 
    commands:
        - mint install realm/SwiftLint
        - mint install nicklockwood/SwiftFormat
        - swiftlint
        - swiftformat --lint Sources

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
