---
kind: pipeline
type: exec
name: build

platform:
  os: darwin
  arch: amd64

# Make sure dependencies for build and lint
# is installed on the build machine

steps:
  - name: lint
    commands:
      - pwd
      - make lint

  - name: build
    commands:
      - brew bundle
      - make build

  - name: install local
    when:
      branch:
        - master
      event:
        - push
    commands:
      - cp ./.build/x86_64-apple-macosx/debug/munin /Users/kradalby/bin/.

  - name: publish build
    when:
      branch:
        - master
      event:
        - push
    commands:
      - make publish
