---
{
   "kind": "pipeline",
   "name": "macOS",
   "platform": {
      "arch": "amd64",
      "os": "darwin"
   },
   "steps": [
      {
         "commands": [
            "brew bundle"
         ],
         "environment": {
            "PATH": "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Ensure tooling",
         "pull": "always"
      },
      {
         "commands": [
            "make lint"
         ],
         "environment": {
            "PATH": "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Lint",
         "pull": "always"
      },
      {
         "commands": [
            "make build"
         ],
         "environment": {
            "PATH": "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Build",
         "pull": "always"
      },
      {
         "commands": [
            "cp ./.build/x86_64-apple-macosx/debug/munin /Users/kradalby/bin/."
         ],
         "name": "Install on local system",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "commands": [
            "make publish"
         ],
         "environment": {
            "PATH": "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet"
         },
         "name": "Publish",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      }
   ],
   "type": "exec"
}
...
