---
kind: pipeline
type: exec
name: build

platform:
  os: darwin
  arch: amd64

steps:
  - name: lint
    commands:
      - brew bundle
      - echo $PATH
      - ls -lah
      - make lint

  - name: build
    commands:
      - brew bundle
      - make build

  - name: install local
    when:
      branch:
        - master
    commands:
      - cp ./.build/x86_64-apple-macosx/debug/munin /Users/kradalby/bin/.

  - name: publish build
    when:
      branch:
        - master
    commands:
      - make publish
