install: build
	cp ./.build/x86_64-apple-macosx/debug/munin ~/bin/.

publish: build
	scp ./.build/x86_64-apple-macosx/debug/munin root@storage.terra.fap.no:/storage/nfs/k8s/builds/munin/.

build:
	sourcery
	swift build

dev:
	swift package generate-xcodeproj

upgrade:
	echo "Not implemented"

clean:
	rm -rf .build

reinstall:
	echo "Not implemented"

lint:
	swiftlint
	swiftformat --exclude Sources/**/Autogenerated --lint Sources

fmt:
	swiftlint autocorrect
	swiftformat Sources
