import Foundation
import Testing

@testable import MuninKit

/// Locks the exact file tree Munin emits for a known input.
///
/// Any change to output naming (per-resolution filename suffixes, symlink
/// placement, keyword shard layout, top-level files like `stats.json` or
/// `locations.json`) will make this test fail. The golden manifest lives
/// in `Tests/MuninKitTests/Fixtures/output-shape.json` and can be
/// regenerated by running `MUNIN_UPDATE_GOLDEN=1 swift test
/// --filter OutputShapeTests`.
///
/// Only paths and kinds are recorded. Byte content (JSON payloads, JPEG
/// bytes) is intentionally NOT locked here because libvips output varies
/// across versions and hosts. Byte-level stability is covered by
/// `StabilityTests` within a single run.
@Suite(.serialized)
struct OutputShapeTests {

  /// Path to the golden manifest, relative to the project root (which is
  /// the CWD during `swift test`).
  private let goldenPath = "Tests/MuninKitTests/Fixtures/output-shape.json"

  @Test func outputShapeMatchesGolden() async throws {
    // Include `Misc` (pure ASCII names, varied JPEG/JPEG extensions) and
    // `2024` (exercises one non-ASCII album folder name, `Håkon_har_nytt_`).
    // The combination keeps the golden small (~40 paths) while exercising
    // the filename transformation, symlink emission, and keyword/people
    // shard layout.
    let fixture = try SourceFixture.stage(albums: ["Misc", "2024"])
    defer { fixture.cleanup() }

    let harness = GalleryHarness(sourceRoot: fixture.sourceRoot, name: "root")
    defer { harness.cleanup() }
    try await harness.build()

    let snapshot = try harness.snapshotOutput()
    let actual = OutputManifest(snapshot: snapshot)

    let cwd = FileManager.default.currentDirectoryPath
    let absGolden = cwd + "/" + goldenPath

    if ProcessInfo.processInfo.environment["MUNIN_UPDATE_GOLDEN"] == "1" {
      try actual.write(toPath: absGolden)
      Issue.record(
        "Updated golden manifest at \(goldenPath). Re-run without MUNIN_UPDATE_GOLDEN to verify.")
      return
    }

    let expected = try OutputManifest.load(fromPath: absGolden)

    let added = Set(actual.entries.map { $0.path }).subtracting(expected.entries.map { $0.path })
    let removed = Set(expected.entries.map { $0.path }).subtracting(actual.entries.map { $0.path })
    #expect(
      added.isEmpty,
      "Output has paths the golden doesn't: \(added.sorted())")
    #expect(
      removed.isEmpty,
      "Golden has paths the output doesn't: \(removed.sorted())")

    // Compare kind per path. Differences here indicate e.g. a symlink
    // becoming a file or vice versa, which would be a material behaviour
    // change.
    let actualByPath = Dictionary(uniqueKeysWithValues: actual.entries.map { ($0.path, $0) })
    let expectedByPath = Dictionary(
      uniqueKeysWithValues: expected.entries.map { ($0.path, $0) })
    for path in Set(actualByPath.keys).intersection(expectedByPath.keys).sorted() {
      #expect(
        actualByPath[path]?.kind == expectedByPath[path]?.kind,
        "kind mismatch at \(path): actual=\(actualByPath[path]?.kind ?? "?") expected=\(expectedByPath[path]?.kind ?? "?")"
      )
    }
  }
}

/// Simple persisted representation of an output tree's shape.
///
/// Lives in the test target — not the library — because it encodes a
/// testing convention (alphabetical order, kind-only) rather than a
/// public API.
struct OutputManifest: Codable, Equatable {

  struct Entry: Codable, Equatable {
    let path: String
    /// One of `"file"`, `"symlink"`, `"directory"`. Stored as String so the
    /// on-disk schema survives changes to `FilesystemSnapshot.Kind`.
    let kind: String
  }

  let entries: [Entry]

  init(snapshot: FilesystemSnapshot) {
    let sortedPaths = snapshot.entries.keys.sorted()
    self.entries = sortedPaths.compactMap { path in
      guard let entry = snapshot.entries[path] else { return nil }
      return Entry(path: path, kind: entry.kind.rawValue)
    }
  }

  private init(entries: [Entry]) {
    self.entries = entries
  }

  func write(toPath path: String) throws {
    let parent = URL(fileURLWithPath: path).deletingLastPathComponent()
    try FileManager.default.createDirectory(
      at: parent, withIntermediateDirectories: true)
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
    let data = try encoder.encode(self)
    try data.write(to: URL(fileURLWithPath: path))
  }

  static func load(fromPath path: String) throws -> OutputManifest {
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    return try JSONDecoder().decode(OutputManifest.self, from: data)
  }
}
