#if !canImport(ObjectiveC)
import XCTest

extension AlbumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlbumTests = [
        ("test", test),
        ("testChangedAlbums", testChangedAlbums),
        ("testChangedAlbumsInputHasChildAlbum", testChangedAlbumsInputHasChildAlbum),
        ("testChangedPhotos", testChangedPhotos),
        ("testClean", testClean),
        ("testExpectedFiles", testExpectedFiles),
        ("testMissingFilesNoOutputDirectory", testMissingFilesNoOutputDirectory),
        ("testMissingFilesWithOutputDirectory", testMissingFilesWithOutputDirectory),
        ("testReadStateFromInputDirectory", testReadStateFromInputDirectory),
        ("testUnreferencedFilesNoOutputDirectory", testUnreferencedFilesNoOutputDirectory),
        ("testUnreferencedFilesWithOutputDirectory", testUnreferencedFilesWithOutputDirectory),
    ]
}

extension GalleryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GalleryTests = [
        ("test", test),
        ("testClean", testClean),
        ("testDiffGalleryAddedAlbum", testDiffGalleryAddedAlbum),
        ("testDiffGalleryAddedPhotos", testDiffGalleryAddedPhotos),
        ("testDiffGalleryNoDiff", testDiffGalleryNoDiff),
        ("testReadInputGallery", testReadInputGallery),
        ("testReadInputOutputGallery", testReadInputOutputGallery),
    ]
}

extension KeywordTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeywordTests = [
        ("test", test),
        ("testBuildKeywordsFromAlbum", testBuildKeywordsFromAlbum),
        ("testPeopleFiles", testPeopleFiles),
        ("testPeopleFilesAuto", testPeopleFilesAuto),
    ]
}

extension LocationDegreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocationDegreeTests = [
        ("test", test),
        ("testLocationDegreeFromDecimal", testLocationDegreeFromDecimal),
        ("testLocationDegreeFromString", testLocationDegreeFromString),
        ("testLocationDegreeToDecimal", testLocationDegreeToDecimal),
    ]
}

extension PhotoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PhotoTests = [
        ("test", test),
        ("testExpectedFiles", testExpectedFiles),
        ("testExpectedValuesRead", testExpectedValuesRead),
        ("testSortWithDateTimes", testSortWithDateTimes),
        ("testSortWithMixDateTimesAndName", testSortWithMixDateTimesAndName),
        ("testSortWithNoDateTimes", testSortWithNoDateTimes),
    ]
}

extension UtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilsTests = [
        ("test", test),
        ("testComputeChangedPhotos", testComputeChangedPhotos),
        ("testComputeChangedPhotosAddedAlbum", testComputeChangedPhotosAddedAlbum),
        ("testComputeChangedPhotosModifiedPhoto", testComputeChangedPhotosModifiedPhoto),
        ("testFindAlbumByName", testFindAlbumByName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlbumTests.__allTests__AlbumTests),
        testCase(GalleryTests.__allTests__GalleryTests),
        testCase(KeywordTests.__allTests__KeywordTests),
        testCase(LocationDegreeTests.__allTests__LocationDegreeTests),
        testCase(PhotoTests.__allTests__PhotoTests),
        testCase(UtilsTests.__allTests__UtilsTests),
    ]
}
#endif
