#if !canImport(ObjectiveC)
import XCTest

extension MuninTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MuninTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MuninTests.__allTests__MuninTests),
    ]
}
#endif
