#!/usr/bin/env bash
# Acceptance test for a statically linked `munin`.
#
#   scripts/smoke-static.sh <binary> --arch amd64|arm64 [--reference DIR]
#
# This stands in for `swift test` on the static artifact. It has to: the Swift
# Static Linux SDK ships no XCTest and no swift-testing, and swift-testing
# 6.3.1 does not compile for musl (glibc-only `siginfo_t.si_status`,
# `RLIMIT_CORE.rawValue`, `backtrace()`). Unit tests stay on the glibc
# toolchain; the static artifact gets this instead, which is arguably stronger
# evidence anyway.
#
# What it proves:
#
#   1. The binary runs on a distro with nothing installed -- `busybox` -- in an
#      empty environment (`env -i`). No host libc, no /usr/share, no locale
#      files, no fontconfig, no ICC profiles. That is the portability
#      assertion; everything else is correctness.
#   2. It builds the whole `example/` gallery to completion and exits 0.
#   3. The tree it produces is byte-for-byte identical to a reference tree.
#   4. libvips' PNG, WebP and TIFF paths survived static linking -- `example/`
#      is all JPEG, so 1-3 pass on a JPEG-only libvips.
#
# Step 3 compares against the committed `example/content` by default. That is
# only meaningful because the staged copy's source mtimes are pinned first:
# Munin writes each source image's mtime into its JSON and git does not
# preserve mtimes, so an unpinned run differs on every fresh checkout. See
# scripts/normalise-mtimes.sh. `--reference DIR` points step 3 at a tree
# generated by the *glibc* build of the same commit instead, which makes this
# a live glibc-vs-musl parity gate rather than a comparison against whatever
# was last committed. Such a tree has to come from a source tree normalised
# the same way; scripts/regen-example-content.sh does both steps.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCKER="${DOCKER:-docker}"
SMOKE_IMAGE="${SMOKE_IMAGE:-busybox}"

USAGE="usage: $(basename "$0") <binary> --arch amd64|arm64 [--reference DIR]"

BIN=""
ARCH=""
REFERENCE="$REPO/example/content"

while [ $# -gt 0 ]; do
  case "$1" in
    --arch)      ARCH="${2:?--arch needs a value}"; shift 2 ;;
    --reference) REFERENCE="${2:?--reference needs a value}"; shift 2 ;;
    -h|--help)   echo "$USAGE"; exit 0 ;;
    -*)          echo "unknown option: $1" >&2; exit 2 ;;
    *)           BIN="$1"; shift ;;
  esac
done

[ -n "$BIN" ] || { echo "$USAGE" >&2; exit 2; }
[ -f "$BIN" ] || { echo "error: no such binary: $BIN" >&2; exit 1; }
BIN="$(cd "$(dirname "$BIN")" && pwd)/$(basename "$BIN")"

# Not inferred from the binary path: the whole test is that this binary runs
# somewhere it was not built, so the path is a bad witness for the arch.
case "$ARCH" in
  amd64|arm64) ;;
  *) echo "error: --arch must be amd64 or arm64" >&2; exit 2 ;;
esac

NORMALISE="$REPO/scripts/normalise-mtimes.sh"

PLATFORM="linux/$ARCH"

# Running a foreign-arch image needs a binfmt handler registered on the host
# *with the F (fix binary) flag* -- without it the kernel looks the interpreter
# up inside the container's mount namespace, where it does not exist, and every
# exec fails with a bare "no such file or directory". NixOS' default
# `boot.binfmt.emulatedSystems` registers with P only, which is not enough.
# On GitHub runners `docker/setup-qemu-action` does the right thing.
if ! $DOCKER run --rm --platform "$PLATFORM" "$SMOKE_IMAGE" true 2>/dev/null; then
  echo "error: cannot run $PLATFORM containers" >&2
  echo "       a binfmt handler registered with the F flag is required; install one with:" >&2
  echo "         $DOCKER run --privileged --rm tonistiigi/binfmt --install $ARCH" >&2
  echo "       (check the current one with: cat /proc/sys/fs/binfmt_misc/*aarch64*)" >&2
  exit 1
fi

WORK="$(mktemp -d)"
FMT="$(mktemp -d)"
LOG="$(mktemp)"
cleanup() {
  # The container writes as root; hand the trees back before removing them.
  $DOCKER run --rm -v "$WORK:/w" -v "$FMT:/f" "$SMOKE_IMAGE" \
    chown -R "$(id -u):$(id -g)" /w /f >/dev/null 2>&1 || true
  rm -rf "$WORK" "$FMT" "$LOG"
}
trap cleanup EXIT

# Run the binary over a staged gallery with nothing inherited: no environment
# (`env -i`), no host libc, no /usr/share, no locale or timezone database, no
# fontconfig, no ICC profiles. The live output stays on the terminal; the
# "N photos has been encoded" count lands in $ENCODED.
ENCODED=""
run_munin() {
  local gallery="$1"
  set +e
  $DOCKER run --rm --platform "$PLATFORM" \
    -v "$gallery:/gallery" \
    -v "$BIN:/munin:ro" \
    -w /gallery \
    "$SMOKE_IMAGE" env -i /munin 2>&1 | tee "$LOG"
  local status="${PIPESTATUS[0]}"
  set -e
  [ "$status" -eq 0 ] || { echo "FAIL: munin exited $status" >&2; exit 1; }

  ENCODED="$(sed -n 's/^[[:space:]]*\([0-9][0-9]*\) photos has been encoded$/\1/p' "$LOG" | tail -1)"
  [ -n "$ENCODED" ] || { echo "FAIL: no 'photos has been encoded' line in output" >&2; exit 1; }
  [ "$ENCODED" -gt 0 ] || { echo "FAIL: $ENCODED photos encoded" >&2; exit 1; }
}

# `cp -a` copies the mtimes too, so the staged album still carries whatever
# the checkout left behind; pin them on the copy. The repository's own
# example/album is untouched -- cp makes new inodes, it does not hardlink.
echo "== staging example/ into $WORK"
cp -a "$REPO/example/." "$WORK/"
rm -rf "$WORK/content"
"$NORMALISE" "$WORK/album"

echo "== running $(basename "$BIN") on $PLATFORM under busybox with an empty environment"
run_munin "$WORK"

FILES="$(find "$WORK/content" -type f | wc -l)"
echo "== $ENCODED photos encoded, $FILES files generated"
[ "$FILES" -gt 0 ] || { echo "FAIL: content/ is empty" >&2; exit 1; }

[ -d "$REFERENCE" ] || { echo "FAIL: reference not a directory: $REFERENCE" >&2; exit 1; }
echo "== diffing against $REFERENCE"
if ! diff -rq "$REFERENCE" "$WORK/content"; then
  echo "FAIL: generated tree differs from the reference" >&2
  echo "      if the difference is in modifiedDate, regenerate the baseline:" >&2
  echo "      scripts/regen-example-content.sh <munin-binary>" >&2
  exit 1
fi
echo "== identical to reference"

# --- PNG / WebP / TIFF ------------------------------------------------------
#
# `example/` is 104 JPEGs, so everything above passes on a libvips that was
# built with JPEG alone. The static libvips also carries libspng, libwebp and
# libtiff, and a decoder that links but does not register is worse than one
# that was never enabled: it fails at the user's runtime instead of at our
# build. So decode a real file in each format and check what comes back out.
#
# Munin names each scaled output after its source extension, so a PNG source
# produces a PNG output -- one gallery run covers both the load and the save
# side of all three. The fixtures were encoded by other people's libraries (see
# scripts/testdata/README.md), which is what makes this a decode test
# rather than a round-trip against ourselves.
FIXTURES="$REPO/scripts/testdata/formats"

# First four bytes as lowercase hex, or bytes [$3, $3+$2) when an offset is
# given. `file(1)` is not assumed to exist; `od` is coreutils.
magic() { od -An -v -tx1 -N "${2:-4}" -j "${3:-0}" "$1" | tr -d ' \n'; }

echo "== staging $FIXTURES into $FMT"
cp -a "$FIXTURES/." "$FMT/"
rm -rf "$FMT/content"
"$NORMALISE" "$FMT/album"

echo "== decoding PNG, WebP and TIFF on $PLATFORM under busybox with an empty environment"
run_munin "$FMT"
[ "$ENCODED" -eq 3 ] || { echo "FAIL: expected 3 photos encoded, got $ENCODED" >&2; exit 1; }

OUT="$FMT/content/formats/Formats"
for f in png_sample_100.png webp_sample_100.webp tiff_sample_100.tif; do
  [ -s "$OUT/$f" ] || { echo "FAIL: $f missing or empty" >&2; exit 1; }
done

# PNG signature; RIFF....WEBP container; TIFF byte-order mark (either endianness).
[ "$(magic "$OUT/png_sample_100.png")" = "89504e47" ] ||
  { echo "FAIL: png_sample_100.png is not a PNG" >&2; exit 1; }
[ "$(magic "$OUT/webp_sample_100.webp")" = "52494646" ] &&
  [ "$(magic "$OUT/webp_sample_100.webp" 4 8)" = "57454250" ] ||
  { echo "FAIL: webp_sample_100.webp is not a WebP" >&2; exit 1; }
case "$(magic "$OUT/tiff_sample_100.tif")" in
  49492a00|4d4d002a) ;;
  *) echo "FAIL: tiff_sample_100.tif is not a TIFF" >&2; exit 1 ;;
esac
echo "== PNG, WebP and TIFF each decoded and re-encoded"

echo "PASS"
