name: Build and Test

on:
  push:
    branches:
      - master
      - main
      - swift-61
      - 'claude/**'
  pull_request:
    branches:
      - master
      - main
      - swift-61

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build project
        id: build
        run: |
          nix build

      - name: Run tests
        id: test
        run: |
          nix develop --command make test
